# Generated by Django 5.0 on 2023-12-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_management', '0003_alter_product_price_alter_sells_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sells',
            name='payment_type',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
