# Generated by Django 5.0 on 2023-12-17 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_management', '0004_sells_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
