# Generated by Django 5.0 on 2023-12-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_management', '0005_remove_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sells',
            name='time_of_sell',
            field=models.DateField(auto_now_add=True),
        ),
    ]
