# Generated by Django 5.0 on 2023-12-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_management', '0007_alter_worker_options_alter_worker_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='value_on_warehouse',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
